version: "3.2"
services:
  front:
    container_name: front
    build: front/.
    ports:
      - 4200:80
    restart: on-failure
    depends_on:
      - back
    links: 
      - back
    networks:
      - arbitrage
    env_file:
      - .env
  back:
    container_name: back
    build: back/.
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    ports:
      - 9091:9091
    networks:
      - arbitrage
  kirin:
    container_name: kirin
    build: kirin/.
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    networks:
      - arbitrage
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - arbitrage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  arbitrage:
    driver: bridge
